ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Force use_frameworks for VeonPrebid compatibility
use_frameworks! :linkage => :static

target 'VeonPrebidReactNativeExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Veon Prebid Dependencies
  pod 'Google-Mobile-Ads-SDK', '12.3.0'
  pod 'VeonPrebidMobile', '0.0.4'
  pod 'VeonPrebidMobileGAMEventHandlers', '0.0.4'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for VeonPrebidMobile module
    installer.pods_project.targets.each do |target|
      if target.name == 'VeonPrebidMobile'
        target.build_configurations.each do |config|
          config.build_settings['DEFINES_MODULE'] = 'YES'
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
      
      if target.name == 'VeonPrebidMobileGAMEventHandlers'
        target.build_configurations.each do |config|
          config.build_settings['DEFINES_MODULE'] = 'YES'
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
    end
  end
end
